export const studentdata = [
  {
    id: 1,
    name: "Nitya",
    rollNo: "B12345",
    courseName: "Web Development Bootcamp",
    startDate: "2023-01-01",
    completionDate: "2023-02-28",
    completedTopics: ["HTML", "CSS", "JavaScript"],
    courseDuration: "120",
    completed: "120",
    remaining: "0",
    remainingTopics: "None",
  },
  {
    id: 2,
    name: "Jane Smith",
    rollNo: "B12346",
    courseName: "React and Frontend Design",
    startDate: "2023-01-05",
    completionDate: "2023-03-15",
    completedTopics: ["HTML", "CSS", "JavaScript", "React"],
    courseDuration: "90",
    completed: "90",
    remaining: "0",
    remainingTopics: "None",
  },
  {
    id: 3,
    name: "Bob Johnson",
    rollNo: "B12347",
    courseName: "CCNA",
    startDate: "2023-01-10",
    completionDate: null,
    completedTopics: [],
    courseDuration: "150",
    completed: "50",
    remaining: "100",
    remainingTopics: [
      "Routing Technologies, WAN Technologies, Infrastructure security",
    ],
  },
  {
    id: 4,
    name: "Alice Brown",
    rollNo: "B12348",
    courseName: "Advanced Web Development",
    startDate: "2023-01-15",
    completionDate: "2023-04-01",
    completedTopics: ["HTML", "CSS", "JavaScript", "React", "Node.js"],
    courseDuration: "110",
    completed: "120",
    remaining: "0",
    remainingTopics: "None",
  },
];
